project:
  type: website
  pre-render: panelize-code-cells-for-quarto-webr.R
website:
  title: webgazeR v0.4.0
  navbar:
    search: true
    right:
      - icon: github
        href: https://github.com/jgeller112/webgazeR
        aria-label: webgazeR GitHub
  sidebar:
    collapse-level: 1
    contents:
      - text: Home
        file: index.qmd
      - section: Articles
        contents:
          - vignettes/ISC.qmd
          - vignettes/webgazeR_vignette.qmd
      - section: Reference
        contents:
          - text: analyze_sampling_rate
            file: man/analyze_sampling_rate.qmd
          - text: assign_aoi
            file: man/assign_aoi.qmd
          - text: calculate_isc
            file: man/calculate_isc.qmd
          - text: downsample_gaze
            file: man/downsample_gaze.qmd
          - text: extract_aois
            file: man/extract_aois.qmd
          - text: filter_sampling_rate
            file: man/filter_sampling_rate.qmd
          - text: find_location
            file: man/find_location.qmd
          - text: gaze_dispersion
            file: man/gaze_dispersion.qmd
          - text: gaze_oob
            file: man/gaze_oob.qmd
          - text: merge_webcam_files
            file: man/merge_webcam_files.qmd
          - text: plot_IA_proportions
            file: man/plot_IA_proportions.qmd
          - text: smooth_gaze
            file: man/smooth_gaze.qmd
          - text: upsample_gaze
            file: man/upsample_gaze.qmd
      - text: License
        file: LICENSE.md
      - text: Citation
        file: CITATION.md
webr:
  packages: webgazeR
  repos: https://jgeller112.github.io/webgazeR/
filters:
  - panelize
  - webr
