## Analyze Sampling Rates for Eye-Tracking Data {.unnumbered}


### Description

This function calculates the sampling rate for each subject and trial in an eye-tracking dataset.
Users can specify whether to compute the mean or median sampling rate. It provides overall statistics,
including the selected measure and standard deviation, and generates a histogram of sampling rates.



### Usage

<pre><code class='language-R'>analyze_sampling_rate(eye_data, summary_stat = "median")
</code></pre>


### Arguments

<table>
<tr><td style = "white-space: collapse; font-family: monospace; vertical-align: top"><code id="eye_data">eye_data</code></td>
<td>
A dataframe containing eye-tracking data with columns 'subject', 'trial', and 'time'.
The column 'time' should represent the time in milliseconds for each trial.
</td></tr>
<tr><td style = "white-space: collapse; font-family: monospace; vertical-align: top"><code id="summary_stat">summary_stat</code></td>
<td>
A character string indicating the summary statistic to use. Must be either '&quot;median&quot;'
(default) or '&quot;mean&quot;'.
</td></tr>
</table>


### Value

A list containing:


<dl>
<dt>overall_summary_SR</dt><dd>The overall mean or median sampling rate (Hz).
</dd>
<dt>overall_sd_SR</dt><dd>The standard deviation of the sampling rate.
</dd>
<dt>summary_SR_by_subject</dt><dd>A dataframe with the mean or median sampling rate by subject.
</dd>
<dt>SR_by_trial</dt><dd>A dataframe with the sampling rate by subject and trial.
</dd>
</dl>



### Examples
::: {.to-webr}
```{r}
#| warning: false
#| message: false
#| eval: false
library("webgazeR")

  # Assuming eye_data is a dataframe with appropriate columns
  result <- analyze_sampling_rate(eye_data, summary_stat = "mean")
  print(result)



```
:::
