
## Assign coordinates to areas of interest {.unnumbered}


### Description

Takes a data frame of gaze positions (or other locations), plus screen size and aoi size (or location), and computes the area of interest (AOI) for each location. Defaults assume standard four-corner design.



### Usage

<pre><code class='language-R'>assign_aoi(
  gaze,
  screen_size = c(1024, 768),
  aoi_size = c(400, 300),
  aoi_loc = NULL,
  X = "CURRENT_FIX_X",
  Y = "CURRENT_FIX_Y"
)
</code></pre>


### Arguments

<table>
<tr><td style = "white-space: collapse; font-family: monospace; vertical-align: top"><code id="gaze">gaze</code></td>
<td>
data frame containing positions
</td></tr>
<tr><td style = "white-space: collapse; font-family: monospace; vertical-align: top"><code id="screen_size">screen_size</code></td>
<td>
size of the screen in pixels. Defaults to c(1024, 768) and assumes reversed vertical (i.e., [0,0] is top left).
</td></tr>
<tr><td style = "white-space: collapse; font-family: monospace; vertical-align: top"><code id="aoi_size">aoi_size</code></td>
<td>
size of AOIs in pixels. Defaults to a c(400, 300) width-height pair and assumes AOIs are in screen corners. AOIs will be coded numerically 1 to 4 in reading order (left to right, top to bottom), with 0 as center location.
</td></tr>
<tr><td style = "white-space: collapse; font-family: monospace; vertical-align: top"><code id="aoi_loc">aoi_loc</code></td>
<td>
location of rectangular AOIs. Use as alternative to aoi_size for non-corner AOIs. Each AOI location should be a separate row in a data frame that has variables xmin, xmax, ymin, and ymax. Assumes reversed vertical (i.e., [0,0] is top left). AOIs will be coded numerically in row order.
</td></tr>
<tr><td style = "white-space: collapse; font-family: monospace; vertical-align: top"><code id="X">X</code></td>
<td>
name of variable containing X coordinates. Defaults to &quot;CURRENT_FIX_X&quot;
</td></tr>
<tr><td style = "white-space: collapse; font-family: monospace; vertical-align: top"><code id="Y">Y</code></td>
<td>
name of variable containing Y coordinates. Defaults to &quot;CURRENT_FIX_Y&quot;
</td></tr>
</table>


### Value

Original gaze data frame with AOI column added. Non-AOI and off-screen gazes are marked NA.


