## Filter or Label Data Based on Sampling Rate Threshold {.unnumbered}


### Description

This function allows users to set a sampling rate threshold and choose to
either remove the data that falls below the threshold or label it as &quot;bad.&quot;
Users can apply this threshold either at the subject level, the trial level,
or both.



### Usage

<pre><code class='language-R'>filter_sampling_rate(
  data,
  threshold = NA,
  action = c("remove", "label"),
  by = c("subject", "trial", "both")
)
</code></pre>


### Arguments

<table>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="data">data</code></td>
<td>
A dataframe that contains the data to be processed. The dataframe
should include the columns:


<dl>
<dt>'subject'</dt><dd>Unique identifier for each participant in the dataset.
</dd>
<dt>'med_SR'</dt><dd>Subject-level median sampling rate (Hz). This represents the median sampling rate for a subject across trials.
</dd>
<dt>'SR'</dt><dd>Trial-level sampling rate (Hz). This represents the sampling rate for each specific trial.
</dd>
</dl>
</td></tr>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="threshold">threshold</code></td>
<td>
Numeric value specifying the sampling rate threshold. Data falling below this threshold will either be removed or labeled as &quot;bad&quot;.
</td></tr>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="action">action</code></td>
<td>
Character string specifying whether to &quot;remove&quot; data that falls below the threshold or &quot;label&quot; it as bad. Acceptable values are '&quot;remove&quot;' or '&quot;label&quot;'.


<dl>
<dt>'&quot;remove&quot;'</dt><dd>Removes rows from the dataset where the sampling rate falls below the threshold.
</dd>
<dt>'&quot;label&quot;'</dt><dd>Adds new columns 'is_bad_subject' and/or 'is_bad_trial' that flag rows where the sampling rate falls below the threshold.
</dd>
</dl>
</td></tr>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="by">by</code></td>
<td>
Character string specifying whether the threshold should be applied
at the &quot;subject&quot; level, the &quot;trial&quot; level, or &quot;both&quot;. Acceptable values are
'&quot;subject&quot;', '&quot;trial&quot;', or '&quot;both&quot;'.


<dl>
<dt>'&quot;subject&quot;'</dt><dd>Applies the threshold to the subject-level median sampling rate ('med_SR').
</dd>
<dt>'&quot;trial&quot;'</dt><dd>Applies the threshold to the trial-level sampling rate ('SR').
</dd>
<dt>'&quot;both&quot;'</dt><dd>Applies the threshold to both the subject-level ('med_SR') and trial-level ('SR') rates. Data is removed/labeled if either rate falls below the threshold.
</dd>
</dl>
</td></tr>
</table>


### Value

A dataframe with either rows removed or new columns ('is_bad_subject', 'is_bad_trial') added
to indicate whether the data is below the threshold. Additionally, messages will inform the user how many subjects and trials were removed or labeled as &quot;bad.&quot;



### Output

The function will either return a dataset with rows removed based on the
sampling rate threshold or add new columns, 'is_bad_subject' and/or 'is_bad_trial' to the dataset,
which indicates whether the data is considered &quot;bad&quot; (i.e., below the
sampling rate threshold).



### Examples
::: {.to-webr}
::: {.to-webr}
```{r}
#| warning: false
#| message: false
#| eval: false
library(webgazeR)

# Example usage of the filter_sampling_rate function
result <- filter_sampling_rate(data = data_with_sr, threshold = 500, action = "remove", by = "both")
# Example usage to label data as "bad"
result <- filter_sampling_rate(data = data_with_sr, threshold = 500, action = "label", by = "trial")



```
:::
:::
